[aws_upload_bucket]
bucket_name = de-ecommerce-datalake
prefix = bronze/raw/olist/
daily_prefix = bronze/daily/

[files_to_not_upload]
files = [olist_geolocation_dataset.csv,olist_sellers_dataset.csv,product_category_name_translation.csv]

[files_to_partition]
files = [olist_orders_dataset.csv,olist_order_items_dataset.csv,olist_order_reviews_dataset.csv]

[dataset_prefix]
olist_customers_dataset.csv = customers 
olist_orders_dataset.csv = orders
olist_order_items_dataset.csv = order_items
olist_order_reviews_dataset.csv = reviews
olist_order_payments_dataset.csv = payments
olist_products_dataset.csv = products

[partition_column]
orders = order_purchase_timestamp
reviews = review_creation_date
order_items = shipping_limit_date

[api_urls]
products = https://dummyjson.com/products
users = https://dummyjson.com/users
